# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import algorithm_pb2 as algorithm__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in algorithm_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AlgoControlServiceStub(object):
    """AlgoControlService defines the API for controlling algorithm execution
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAvailableSchemes = channel.unary_unary(
                '/algorithm.AlgoControlService/GetAvailableSchemes',
                request_serializer=algorithm__pb2.Empty.SerializeToString,
                response_deserializer=algorithm__pb2.SchemeList.FromString,
                _registered_method=True)
        self.SubmitTask = channel.unary_unary(
                '/algorithm.AlgoControlService/SubmitTask',
                request_serializer=algorithm__pb2.TaskRequest.SerializeToString,
                response_deserializer=algorithm__pb2.TaskSubmissionResponse.FromString,
                _registered_method=True)
        self.CheckHealth = channel.unary_unary(
                '/algorithm.AlgoControlService/CheckHealth',
                request_serializer=algorithm__pb2.Empty.SerializeToString,
                response_deserializer=algorithm__pb2.HealthStatus.FromString,
                _registered_method=True)
        self.WatchTaskProgress = channel.unary_stream(
                '/algorithm.AlgoControlService/WatchTaskProgress',
                request_serializer=algorithm__pb2.TaskIdentity.SerializeToString,
                response_deserializer=algorithm__pb2.ProgressUpdate.FromString,
                _registered_method=True)
        self.ListTasks = channel.unary_unary(
                '/algorithm.AlgoControlService/ListTasks',
                request_serializer=algorithm__pb2.Empty.SerializeToString,
                response_deserializer=algorithm__pb2.TaskList.FromString,
                _registered_method=True)
        self.GetTaskStatus = channel.unary_unary(
                '/algorithm.AlgoControlService/GetTaskStatus',
                request_serializer=algorithm__pb2.TaskIdentity.SerializeToString,
                response_deserializer=algorithm__pb2.TaskStatus.FromString,
                _registered_method=True)
        self.CancelTask = channel.unary_unary(
                '/algorithm.AlgoControlService/CancelTask',
                request_serializer=algorithm__pb2.CancelRequest.SerializeToString,
                response_deserializer=algorithm__pb2.CancelResponse.FromString,
                _registered_method=True)


class AlgoControlServiceServicer(object):
    """AlgoControlService defines the API for controlling algorithm execution
    """

    def GetAvailableSchemes(self, request, context):
        """GetAvailableSchemes returns all registered algorithm schemes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitTask(self, request, context):
        """SubmitTask submits a new algorithm task for processing
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckHealth(self, request, context):
        """CheckHealth returns the health status of the algorithm service
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchTaskProgress(self, request, context):
        """WatchTaskProgress streams real-time progress updates for a task
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTasks(self, request, context):
        """ListTasks returns all known tasks and their statuses
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTaskStatus(self, request, context):
        """GetTaskStatus returns the current status of a specific task
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelTask(self, request, context):
        """CancelTask requests cancellation of a task
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AlgoControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAvailableSchemes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvailableSchemes,
                    request_deserializer=algorithm__pb2.Empty.FromString,
                    response_serializer=algorithm__pb2.SchemeList.SerializeToString,
            ),
            'SubmitTask': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitTask,
                    request_deserializer=algorithm__pb2.TaskRequest.FromString,
                    response_serializer=algorithm__pb2.TaskSubmissionResponse.SerializeToString,
            ),
            'CheckHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckHealth,
                    request_deserializer=algorithm__pb2.Empty.FromString,
                    response_serializer=algorithm__pb2.HealthStatus.SerializeToString,
            ),
            'WatchTaskProgress': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchTaskProgress,
                    request_deserializer=algorithm__pb2.TaskIdentity.FromString,
                    response_serializer=algorithm__pb2.ProgressUpdate.SerializeToString,
            ),
            'ListTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTasks,
                    request_deserializer=algorithm__pb2.Empty.FromString,
                    response_serializer=algorithm__pb2.TaskList.SerializeToString,
            ),
            'GetTaskStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTaskStatus,
                    request_deserializer=algorithm__pb2.TaskIdentity.FromString,
                    response_serializer=algorithm__pb2.TaskStatus.SerializeToString,
            ),
            'CancelTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelTask,
                    request_deserializer=algorithm__pb2.CancelRequest.FromString,
                    response_serializer=algorithm__pb2.CancelResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'algorithm.AlgoControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('algorithm.AlgoControlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AlgoControlService(object):
    """AlgoControlService defines the API for controlling algorithm execution
    """

    @staticmethod
    def GetAvailableSchemes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/algorithm.AlgoControlService/GetAvailableSchemes',
            algorithm__pb2.Empty.SerializeToString,
            algorithm__pb2.SchemeList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/algorithm.AlgoControlService/SubmitTask',
            algorithm__pb2.TaskRequest.SerializeToString,
            algorithm__pb2.TaskSubmissionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/algorithm.AlgoControlService/CheckHealth',
            algorithm__pb2.Empty.SerializeToString,
            algorithm__pb2.HealthStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchTaskProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/algorithm.AlgoControlService/WatchTaskProgress',
            algorithm__pb2.TaskIdentity.SerializeToString,
            algorithm__pb2.ProgressUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/algorithm.AlgoControlService/ListTasks',
            algorithm__pb2.Empty.SerializeToString,
            algorithm__pb2.TaskList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTaskStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/algorithm.AlgoControlService/GetTaskStatus',
            algorithm__pb2.TaskIdentity.SerializeToString,
            algorithm__pb2.TaskStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/algorithm.AlgoControlService/CancelTask',
            algorithm__pb2.CancelRequest.SerializeToString,
            algorithm__pb2.CancelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ResultReceiverServiceStub(object):
    """ResultReceiverService receives results from the algorithm service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReportResult = channel.unary_unary(
                '/algorithm.ResultReceiverService/ReportResult',
                request_serializer=algorithm__pb2.TaskResult.SerializeToString,
                response_deserializer=algorithm__pb2.Ack.FromString,
                _registered_method=True)


class ResultReceiverServiceServicer(object):
    """ResultReceiverService receives results from the algorithm service
    """

    def ReportResult(self, request, context):
        """ReportResult reports the completion of a task
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ResultReceiverServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReportResult': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportResult,
                    request_deserializer=algorithm__pb2.TaskResult.FromString,
                    response_serializer=algorithm__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'algorithm.ResultReceiverService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('algorithm.ResultReceiverService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ResultReceiverService(object):
    """ResultReceiverService receives results from the algorithm service
    """

    @staticmethod
    def ReportResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/algorithm.ResultReceiverService/ReportResult',
            algorithm__pb2.TaskResult.SerializeToString,
            algorithm__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
