// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/algorithm.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskResult_Status int32

const (
	TaskResult_SUCCESS   TaskResult_Status = 0
	TaskResult_FAILED    TaskResult_Status = 1
	TaskResult_CANCELLED TaskResult_Status = 2
	TaskResult_TIMEOUT   TaskResult_Status = 3
)

// Enum value maps for TaskResult_Status.
var (
	TaskResult_Status_name = map[int32]string{
		0: "SUCCESS",
		1: "FAILED",
		2: "CANCELLED",
		3: "TIMEOUT",
	}
	TaskResult_Status_value = map[string]int32{
		"SUCCESS":   0,
		"FAILED":    1,
		"CANCELLED": 2,
		"TIMEOUT":   3,
	}
)

func (x TaskResult_Status) Enum() *TaskResult_Status {
	p := new(TaskResult_Status)
	*p = x
	return p
}

func (x TaskResult_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskResult_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_algorithm_proto_enumTypes[0].Descriptor()
}

func (TaskResult_Status) Type() protoreflect.EnumType {
	return &file_proto_algorithm_proto_enumTypes[0]
}

func (x TaskResult_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskResult_Status.Descriptor instead.
func (TaskResult_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_algorithm_proto_rawDescGZIP(), []int{6, 0}
}

type HealthStatus_ServingStatus int32

const (
	HealthStatus_UNKNOWN     HealthStatus_ServingStatus = 0
	HealthStatus_SERVING     HealthStatus_ServingStatus = 1
	HealthStatus_NOT_SERVING HealthStatus_ServingStatus = 2
)

// Enum value maps for HealthStatus_ServingStatus.
var (
	HealthStatus_ServingStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
	}
	HealthStatus_ServingStatus_value = map[string]int32{
		"UNKNOWN":     0,
		"SERVING":     1,
		"NOT_SERVING": 2,
	}
)

func (x HealthStatus_ServingStatus) Enum() *HealthStatus_ServingStatus {
	p := new(HealthStatus_ServingStatus)
	*p = x
	return p
}

func (x HealthStatus_ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthStatus_ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_algorithm_proto_enumTypes[1].Descriptor()
}

func (HealthStatus_ServingStatus) Type() protoreflect.EnumType {
	return &file_proto_algorithm_proto_enumTypes[1]
}

func (x HealthStatus_ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthStatus_ServingStatus.Descriptor instead.
func (HealthStatus_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_algorithm_proto_rawDescGZIP(), []int{7, 0}
}

type SchemeList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schemes       []*SchemeList_Scheme   `protobuf:"bytes,1,rep,name=schemes,proto3" json:"schemes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemeList) Reset() {
	*x = SchemeList{}
	mi := &file_proto_algorithm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemeList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemeList) ProtoMessage() {}

func (x *SchemeList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_algorithm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemeList.ProtoReflect.Descriptor instead.
func (*SchemeList) Descriptor() ([]byte, []int) {
	return file_proto_algorithm_proto_rawDescGZIP(), []int{0}
}

func (x *SchemeList) GetSchemes() []*SchemeList_Scheme {
	if x != nil {
		return x.Schemes
	}
	return nil
}

type TaskRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	SchemeCode     string                 `protobuf:"bytes,2,opt,name=scheme_code,json=schemeCode,proto3" json:"scheme_code,omitempty"`
	DataRef        string                 `protobuf:"bytes,3,opt,name=data_ref,json=dataRef,proto3" json:"data_ref,omitempty"`
	ParamsJson     string                 `protobuf:"bytes,4,opt,name=params_json,json=paramsJson,proto3" json:"params_json,omitempty"`
	Priority       int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`                                   // Task priority (higher = more urgent)
	TimeoutSeconds int32                  `protobuf:"varint,6,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"` // Maximum execution time
	CallbackUrl    string                 `protobuf:"bytes,7,opt,name=callback_url,json=callbackUrl,proto3" json:"callback_url,omitempty"`           // Optional HTTP callback URL
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_proto_algorithm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_algorithm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_algorithm_proto_rawDescGZIP(), []int{1}
}

func (x *TaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskRequest) GetSchemeCode() string {
	if x != nil {
		return x.SchemeCode
	}
	return ""
}

func (x *TaskRequest) GetDataRef() string {
	if x != nil {
		return x.DataRef
	}
	return ""
}

func (x *TaskRequest) GetParamsJson() string {
	if x != nil {
		return x.ParamsJson
	}
	return ""
}

func (x *TaskRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *TaskRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *TaskRequest) GetCallbackUrl() string {
	if x != nil {
		return x.CallbackUrl
	}
	return ""
}

type TaskSubmissionResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Accepted       bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	QueuePosition  int32                  `protobuf:"varint,3,opt,name=queue_position,json=queuePosition,proto3" json:"queue_position,omitempty"`    // Position in processing queue
	EstimatedStart int64                  `protobuf:"varint,4,opt,name=estimated_start,json=estimatedStart,proto3" json:"estimated_start,omitempty"` // Estimated start timestamp
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TaskSubmissionResponse) Reset() {
	*x = TaskSubmissionResponse{}
	mi := &file_proto_algorithm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskSubmissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskSubmissionResponse) ProtoMessage() {}

func (x *TaskSubmissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_algorithm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskSubmissionResponse.ProtoReflect.Descriptor instead.
func (*TaskSubmissionResponse) Descriptor() ([]byte, []int) {
	return file_proto_algorithm_proto_rawDescGZIP(), []int{2}
}

func (x *TaskSubmissionResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *TaskSubmissionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TaskSubmissionResponse) GetQueuePosition() int32 {
	if x != nil {
		return x.QueuePosition
	}
	return 0
}

func (x *TaskSubmissionResponse) GetEstimatedStart() int64 {
	if x != nil {
		return x.EstimatedStart
	}
	return 0
}

type CancelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // Current status after cancel request
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelResponse) Reset() {
	*x = CancelResponse{}
	mi := &file_proto_algorithm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResponse) ProtoMessage() {}

func (x *CancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_algorithm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResponse.ProtoReflect.Descriptor instead.
func (*CancelResponse) Descriptor() ([]byte, []int) {
	return file_proto_algorithm_proto_rawDescGZIP(), []int{3}
}

func (x *CancelResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *CancelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CancelResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"` // If true, immediately force-kill the process
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_proto_algorithm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_algorithm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_proto_algorithm_proto_rawDescGZIP(), []int{4}
}

func (x *CancelRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CancelRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type ProgressUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Percentage    int32                  `protobuf:"varint,2,opt,name=percentage,proto3" json:"percentage,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Stage         string                 `protobuf:"bytes,5,opt,name=stage,proto3" json:"stage,omitempty"`                                                                               // Current processing stage
	Metrics       map[string]string      `protobuf:"bytes,6,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Real-time metrics
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressUpdate) Reset() {
	*x = ProgressUpdate{}
	mi := &file_proto_algorithm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressUpdate) ProtoMessage() {}

func (x *ProgressUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_algorithm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressUpdate.ProtoReflect.Descriptor instead.
func (*ProgressUpdate) Descriptor() ([]byte, []int) {
	return file_proto_algorithm_proto_rawDescGZIP(), []int{5}
}

func (x *ProgressUpdate) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ProgressUpdate) GetPercentage() int32 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

func (x *ProgressUpdate) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProgressUpdate) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ProgressUpdate) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *ProgressUpdate) GetMetrics() map[string]string {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type TaskResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        TaskResult_Status      `protobuf:"varint,2,opt,name=status,proto3,enum=algorithm.TaskResult_Status" json:"status,omitempty"`
	ResultJson    string                 `protobuf:"bytes,3,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	LogPath       string                 `protobuf:"bytes,5,opt,name=log_path,json=logPath,proto3" json:"log_path,omitempty"`
	DurationMs    int64                  `protobuf:"varint,6,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"` // Actual execution duration
	Metrics       map[string]string      `protobuf:"bytes,7,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_proto_algorithm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_algorithm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_proto_algorithm_proto_rawDescGZIP(), []int{6}
}

func (x *TaskResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResult) GetStatus() TaskResult_Status {
	if x != nil {
		return x.Status
	}
	return TaskResult_SUCCESS
}

func (x *TaskResult) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

func (x *TaskResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TaskResult) GetLogPath() string {
	if x != nil {
		return x.LogPath
	}
	return ""
}

func (x *TaskResult) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *TaskResult) GetMetrics() map[string]string {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// DataChunk for streaming large files
type HealthStatus struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Status        HealthStatus_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=algorithm.HealthStatus_ServingStatus" json:"status,omitempty"`
	Metrics       map[string]string          `protobuf:"bytes,2,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ActiveTasks   int32                      `protobuf:"varint,3,opt,name=active_tasks,json=activeTasks,proto3" json:"active_tasks,omitempty"`
	QueueLength   int32                      `protobuf:"varint,4,opt,name=queue_length,json=queueLength,proto3" json:"queue_length,omitempty"`
	CpuUsage      float64                    `protobuf:"fixed64,5,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsage   float64                    `protobuf:"fixed64,6,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	GpuAvailable  bool                       `protobuf:"varint,7,opt,name=gpu_available,json=gpuAvailable,proto3" json:"gpu_available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthStatus) Reset() {
	*x = HealthStatus{}
	mi := &file_proto_algorithm_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthStatus) ProtoMessage() {}

func (x *HealthStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_algorithm_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthStatus.ProtoReflect.Descriptor instead.
func (*HealthStatus) Descriptor() ([]byte, []int) {
	return file_proto_algorithm_proto_rawDescGZIP(), []int{7}
}

func (x *HealthStatus) GetStatus() HealthStatus_ServingStatus {
	if x != nil {
		return x.Status
	}
	return HealthStatus_UNKNOWN
}

func (x *HealthStatus) GetMetrics() map[string]string {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *HealthStatus) GetActiveTasks() int32 {
	if x != nil {
		return x.ActiveTasks
	}
	return 0
}

func (x *HealthStatus) GetQueueLength() int32 {
	if x != nil {
		return x.QueueLength
	}
	return 0
}

func (x *HealthStatus) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *HealthStatus) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *HealthStatus) GetGpuAvailable() bool {
	if x != nil {
		return x.GpuAvailable
	}
	return false
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_algorithm_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_algorithm_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_algorithm_proto_rawDescGZIP(), []int{8}
}

type TaskIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskIdentity) Reset() {
	*x = TaskIdentity{}
	mi := &file_proto_algorithm_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskIdentity) ProtoMessage() {}

func (x *TaskIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_algorithm_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskIdentity.ProtoReflect.Descriptor instead.
func (*TaskIdentity) Descriptor() ([]byte, []int) {
	return file_proto_algorithm_proto_rawDescGZIP(), []int{9}
}

func (x *TaskIdentity) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_algorithm_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_algorithm_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_algorithm_proto_rawDescGZIP(), []int{10}
}

func (x *Ack) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Ack) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TaskStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	SchemeCode    string                 `protobuf:"bytes,2,opt,name=scheme_code,json=schemeCode,proto3" json:"scheme_code,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Percentage    int32                  `protobuf:"varint,4,opt,name=percentage,proto3" json:"percentage,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	FinishedAt    int64                  `protobuf:"varint,9,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStatus) Reset() {
	*x = TaskStatus{}
	mi := &file_proto_algorithm_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatus) ProtoMessage() {}

func (x *TaskStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_algorithm_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatus.ProtoReflect.Descriptor instead.
func (*TaskStatus) Descriptor() ([]byte, []int) {
	return file_proto_algorithm_proto_rawDescGZIP(), []int{11}
}

func (x *TaskStatus) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskStatus) GetSchemeCode() string {
	if x != nil {
		return x.SchemeCode
	}
	return ""
}

func (x *TaskStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TaskStatus) GetPercentage() int32 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

func (x *TaskStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TaskStatus) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TaskStatus) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *TaskStatus) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *TaskStatus) GetFinishedAt() int64 {
	if x != nil {
		return x.FinishedAt
	}
	return 0
}

type TaskList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*TaskStatus          `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Pending       int32                  `protobuf:"varint,3,opt,name=pending,proto3" json:"pending,omitempty"`
	Running       int32                  `protobuf:"varint,4,opt,name=running,proto3" json:"running,omitempty"`
	Completed     int32                  `protobuf:"varint,5,opt,name=completed,proto3" json:"completed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskList) Reset() {
	*x = TaskList{}
	mi := &file_proto_algorithm_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskList) ProtoMessage() {}

func (x *TaskList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_algorithm_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskList.ProtoReflect.Descriptor instead.
func (*TaskList) Descriptor() ([]byte, []int) {
	return file_proto_algorithm_proto_rawDescGZIP(), []int{12}
}

func (x *TaskList) GetTasks() []*TaskStatus {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *TaskList) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *TaskList) GetPending() int32 {
	if x != nil {
		return x.Pending
	}
	return 0
}

func (x *TaskList) GetRunning() int32 {
	if x != nil {
		return x.Running
	}
	return 0
}

func (x *TaskList) GetCompleted() int32 {
	if x != nil {
		return x.Completed
	}
	return 0
}

type SchemeList_Scheme struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Model          string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Code           string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ClassName      string                 `protobuf:"bytes,4,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`
	ResourceType   string                 `protobuf:"bytes,5,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	Description    string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	RequiredParams []string               `protobuf:"bytes,7,rep,name=required_params,json=requiredParams,proto3" json:"required_params,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SchemeList_Scheme) Reset() {
	*x = SchemeList_Scheme{}
	mi := &file_proto_algorithm_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemeList_Scheme) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemeList_Scheme) ProtoMessage() {}

func (x *SchemeList_Scheme) ProtoReflect() protoreflect.Message {
	mi := &file_proto_algorithm_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemeList_Scheme.ProtoReflect.Descriptor instead.
func (*SchemeList_Scheme) Descriptor() ([]byte, []int) {
	return file_proto_algorithm_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SchemeList_Scheme) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *SchemeList_Scheme) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SchemeList_Scheme) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SchemeList_Scheme) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *SchemeList_Scheme) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *SchemeList_Scheme) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SchemeList_Scheme) GetRequiredParams() []string {
	if x != nil {
		return x.RequiredParams
	}
	return nil
}

var File_proto_algorithm_proto protoreflect.FileDescriptor

const file_proto_algorithm_proto_rawDesc = "" +
	"\n" +
	"\x15proto/algorithm.proto\x12\talgorithm\"\x9c\x02\n" +
	"\n" +
	"SchemeList\x126\n" +
	"\aschemes\x18\x01 \x03(\v2\x1c.algorithm.SchemeList.SchemeR\aschemes\x1a\xd5\x01\n" +
	"\x06Scheme\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"class_name\x18\x04 \x01(\tR\tclassName\x12#\n" +
	"\rresource_type\x18\x05 \x01(\tR\fresourceType\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12'\n" +
	"\x0frequired_params\x18\a \x03(\tR\x0erequiredParams\"\xeb\x01\n" +
	"\vTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1f\n" +
	"\vscheme_code\x18\x02 \x01(\tR\n" +
	"schemeCode\x12\x19\n" +
	"\bdata_ref\x18\x03 \x01(\tR\adataRef\x12\x1f\n" +
	"\vparams_json\x18\x04 \x01(\tR\n" +
	"paramsJson\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x12'\n" +
	"\x0ftimeout_seconds\x18\x06 \x01(\x05R\x0etimeoutSeconds\x12!\n" +
	"\fcallback_url\x18\a \x01(\tR\vcallbackUrl\"\x9e\x01\n" +
	"\x16TaskSubmissionResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x0equeue_position\x18\x03 \x01(\x05R\rqueuePosition\x12'\n" +
	"\x0festimated_start\x18\x04 \x01(\x03R\x0eestimatedStart\"^\n" +
	"\x0eCancelResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\">\n" +
	"\rCancelRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"\x95\x02\n" +
	"\x0eProgressUpdate\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1e\n" +
	"\n" +
	"percentage\x18\x02 \x01(\x05R\n" +
	"percentage\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05stage\x18\x05 \x01(\tR\x05stage\x12@\n" +
	"\ametrics\x18\x06 \x03(\v2&.algorithm.ProgressUpdate.MetricsEntryR\ametrics\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x96\x03\n" +
	"\n" +
	"TaskResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x124\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1c.algorithm.TaskResult.StatusR\x06status\x12\x1f\n" +
	"\vresult_json\x18\x03 \x01(\tR\n" +
	"resultJson\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12\x19\n" +
	"\blog_path\x18\x05 \x01(\tR\alogPath\x12\x1f\n" +
	"\vduration_ms\x18\x06 \x01(\x03R\n" +
	"durationMs\x12<\n" +
	"\ametrics\x18\a \x03(\v2\".algorithm.TaskResult.MetricsEntryR\ametrics\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"=\n" +
	"\x06Status\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\n" +
	"\n" +
	"\x06FAILED\x10\x01\x12\r\n" +
	"\tCANCELLED\x10\x02\x12\v\n" +
	"\aTIMEOUT\x10\x03\"\xb0\x03\n" +
	"\fHealthStatus\x12=\n" +
	"\x06status\x18\x01 \x01(\x0e2%.algorithm.HealthStatus.ServingStatusR\x06status\x12>\n" +
	"\ametrics\x18\x02 \x03(\v2$.algorithm.HealthStatus.MetricsEntryR\ametrics\x12!\n" +
	"\factive_tasks\x18\x03 \x01(\x05R\vactiveTasks\x12!\n" +
	"\fqueue_length\x18\x04 \x01(\x05R\vqueueLength\x12\x1b\n" +
	"\tcpu_usage\x18\x05 \x01(\x01R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x06 \x01(\x01R\vmemoryUsage\x12#\n" +
	"\rgpu_available\x18\a \x01(\bR\fgpuAvailable\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\":\n" +
	"\rServingStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x02\"\a\n" +
	"\x05Empty\"'\n" +
	"\fTaskIdentity\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"9\n" +
	"\x03Ack\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x9c\x02\n" +
	"\n" +
	"TaskStatus\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1f\n" +
	"\vscheme_code\x18\x02 \x01(\tR\n" +
	"schemeCode\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"percentage\x18\x04 \x01(\x05R\n" +
	"percentage\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\x03R\tupdatedAt\x12\x1f\n" +
	"\vfinished_at\x18\t \x01(\x03R\n" +
	"finishedAt\"\x9f\x01\n" +
	"\bTaskList\x12+\n" +
	"\x05tasks\x18\x01 \x03(\v2\x15.algorithm.TaskStatusR\x05tasks\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x18\n" +
	"\apending\x18\x03 \x01(\x05R\apending\x12\x18\n" +
	"\arunning\x18\x04 \x01(\x05R\arunning\x12\x1c\n" +
	"\tcompleted\x18\x05 \x01(\x05R\tcompleted2\xda\x03\n" +
	"\x12AlgoControlService\x12>\n" +
	"\x13GetAvailableSchemes\x12\x10.algorithm.Empty\x1a\x15.algorithm.SchemeList\x12G\n" +
	"\n" +
	"SubmitTask\x12\x16.algorithm.TaskRequest\x1a!.algorithm.TaskSubmissionResponse\x128\n" +
	"\vCheckHealth\x12\x10.algorithm.Empty\x1a\x17.algorithm.HealthStatus\x12I\n" +
	"\x11WatchTaskProgress\x12\x17.algorithm.TaskIdentity\x1a\x19.algorithm.ProgressUpdate0\x01\x122\n" +
	"\tListTasks\x12\x10.algorithm.Empty\x1a\x13.algorithm.TaskList\x12?\n" +
	"\rGetTaskStatus\x12\x17.algorithm.TaskIdentity\x1a\x15.algorithm.TaskStatus\x12A\n" +
	"\n" +
	"CancelTask\x12\x18.algorithm.CancelRequest\x1a\x19.algorithm.CancelResponse2N\n" +
	"\x15ResultReceiverService\x125\n" +
	"\fReportResult\x12\x15.algorithm.TaskResult\x1a\x0e.algorithm.AckB7Z5github.com/electric-power/backend-service/proto;protob\x06proto3"

var (
	file_proto_algorithm_proto_rawDescOnce sync.Once
	file_proto_algorithm_proto_rawDescData []byte
)

func file_proto_algorithm_proto_rawDescGZIP() []byte {
	file_proto_algorithm_proto_rawDescOnce.Do(func() {
		file_proto_algorithm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_algorithm_proto_rawDesc), len(file_proto_algorithm_proto_rawDesc)))
	})
	return file_proto_algorithm_proto_rawDescData
}

var file_proto_algorithm_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_algorithm_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_algorithm_proto_goTypes = []any{
	(TaskResult_Status)(0),          // 0: algorithm.TaskResult.Status
	(HealthStatus_ServingStatus)(0), // 1: algorithm.HealthStatus.ServingStatus
	(*SchemeList)(nil),              // 2: algorithm.SchemeList
	(*TaskRequest)(nil),             // 3: algorithm.TaskRequest
	(*TaskSubmissionResponse)(nil),  // 4: algorithm.TaskSubmissionResponse
	(*CancelResponse)(nil),          // 5: algorithm.CancelResponse
	(*CancelRequest)(nil),           // 6: algorithm.CancelRequest
	(*ProgressUpdate)(nil),          // 7: algorithm.ProgressUpdate
	(*TaskResult)(nil),              // 8: algorithm.TaskResult
	(*HealthStatus)(nil),            // 9: algorithm.HealthStatus
	(*Empty)(nil),                   // 10: algorithm.Empty
	(*TaskIdentity)(nil),            // 11: algorithm.TaskIdentity
	(*Ack)(nil),                     // 12: algorithm.Ack
	(*TaskStatus)(nil),              // 13: algorithm.TaskStatus
	(*TaskList)(nil),                // 14: algorithm.TaskList
	(*SchemeList_Scheme)(nil),       // 15: algorithm.SchemeList.Scheme
	nil,                             // 16: algorithm.ProgressUpdate.MetricsEntry
	nil,                             // 17: algorithm.TaskResult.MetricsEntry
	nil,                             // 18: algorithm.HealthStatus.MetricsEntry
}
var file_proto_algorithm_proto_depIdxs = []int32{
	15, // 0: algorithm.SchemeList.schemes:type_name -> algorithm.SchemeList.Scheme
	16, // 1: algorithm.ProgressUpdate.metrics:type_name -> algorithm.ProgressUpdate.MetricsEntry
	0,  // 2: algorithm.TaskResult.status:type_name -> algorithm.TaskResult.Status
	17, // 3: algorithm.TaskResult.metrics:type_name -> algorithm.TaskResult.MetricsEntry
	1,  // 4: algorithm.HealthStatus.status:type_name -> algorithm.HealthStatus.ServingStatus
	18, // 5: algorithm.HealthStatus.metrics:type_name -> algorithm.HealthStatus.MetricsEntry
	13, // 6: algorithm.TaskList.tasks:type_name -> algorithm.TaskStatus
	10, // 7: algorithm.AlgoControlService.GetAvailableSchemes:input_type -> algorithm.Empty
	3,  // 8: algorithm.AlgoControlService.SubmitTask:input_type -> algorithm.TaskRequest
	10, // 9: algorithm.AlgoControlService.CheckHealth:input_type -> algorithm.Empty
	11, // 10: algorithm.AlgoControlService.WatchTaskProgress:input_type -> algorithm.TaskIdentity
	10, // 11: algorithm.AlgoControlService.ListTasks:input_type -> algorithm.Empty
	11, // 12: algorithm.AlgoControlService.GetTaskStatus:input_type -> algorithm.TaskIdentity
	6,  // 13: algorithm.AlgoControlService.CancelTask:input_type -> algorithm.CancelRequest
	8,  // 14: algorithm.ResultReceiverService.ReportResult:input_type -> algorithm.TaskResult
	2,  // 15: algorithm.AlgoControlService.GetAvailableSchemes:output_type -> algorithm.SchemeList
	4,  // 16: algorithm.AlgoControlService.SubmitTask:output_type -> algorithm.TaskSubmissionResponse
	9,  // 17: algorithm.AlgoControlService.CheckHealth:output_type -> algorithm.HealthStatus
	7,  // 18: algorithm.AlgoControlService.WatchTaskProgress:output_type -> algorithm.ProgressUpdate
	14, // 19: algorithm.AlgoControlService.ListTasks:output_type -> algorithm.TaskList
	13, // 20: algorithm.AlgoControlService.GetTaskStatus:output_type -> algorithm.TaskStatus
	5,  // 21: algorithm.AlgoControlService.CancelTask:output_type -> algorithm.CancelResponse
	12, // 22: algorithm.ResultReceiverService.ReportResult:output_type -> algorithm.Ack
	15, // [15:23] is the sub-list for method output_type
	7,  // [7:15] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_algorithm_proto_init() }
func file_proto_algorithm_proto_init() {
	if File_proto_algorithm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_algorithm_proto_rawDesc), len(file_proto_algorithm_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_algorithm_proto_goTypes,
		DependencyIndexes: file_proto_algorithm_proto_depIdxs,
		EnumInfos:         file_proto_algorithm_proto_enumTypes,
		MessageInfos:      file_proto_algorithm_proto_msgTypes,
	}.Build()
	File_proto_algorithm_proto = out.File
	file_proto_algorithm_proto_goTypes = nil
	file_proto_algorithm_proto_depIdxs = nil
}
