// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: proto/algorithm.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AlgoControlService_GetAvailableSchemes_FullMethodName = "/algorithm.AlgoControlService/GetAvailableSchemes"
	AlgoControlService_SubmitTask_FullMethodName          = "/algorithm.AlgoControlService/SubmitTask"
	AlgoControlService_CheckHealth_FullMethodName         = "/algorithm.AlgoControlService/CheckHealth"
	AlgoControlService_WatchTaskProgress_FullMethodName   = "/algorithm.AlgoControlService/WatchTaskProgress"
	AlgoControlService_ListTasks_FullMethodName           = "/algorithm.AlgoControlService/ListTasks"
	AlgoControlService_GetTaskStatus_FullMethodName       = "/algorithm.AlgoControlService/GetTaskStatus"
	AlgoControlService_CancelTask_FullMethodName          = "/algorithm.AlgoControlService/CancelTask"
)

// AlgoControlServiceClient is the client API for AlgoControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AlgoControlService defines the API for controlling algorithm execution
type AlgoControlServiceClient interface {
	// GetAvailableSchemes returns all registered algorithm schemes
	GetAvailableSchemes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SchemeList, error)
	// SubmitTask submits a new algorithm task for processing
	SubmitTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskSubmissionResponse, error)
	// CheckHealth returns the health status of the algorithm service
	CheckHealth(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthStatus, error)
	// WatchTaskProgress streams real-time progress updates for a task
	WatchTaskProgress(ctx context.Context, in *TaskIdentity, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProgressUpdate], error)
	// ListTasks returns all known tasks and their statuses
	ListTasks(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TaskList, error)
	// GetTaskStatus returns the current status of a specific task
	GetTaskStatus(ctx context.Context, in *TaskIdentity, opts ...grpc.CallOption) (*TaskStatus, error)
	// CancelTask requests cancellation of a task
	CancelTask(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*CancelResponse, error)
}

type algoControlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAlgoControlServiceClient(cc grpc.ClientConnInterface) AlgoControlServiceClient {
	return &algoControlServiceClient{cc}
}

func (c *algoControlServiceClient) GetAvailableSchemes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SchemeList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SchemeList)
	err := c.cc.Invoke(ctx, AlgoControlService_GetAvailableSchemes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *algoControlServiceClient) SubmitTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskSubmissionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskSubmissionResponse)
	err := c.cc.Invoke(ctx, AlgoControlService_SubmitTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *algoControlServiceClient) CheckHealth(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthStatus)
	err := c.cc.Invoke(ctx, AlgoControlService_CheckHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *algoControlServiceClient) WatchTaskProgress(ctx context.Context, in *TaskIdentity, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProgressUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AlgoControlService_ServiceDesc.Streams[0], AlgoControlService_WatchTaskProgress_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TaskIdentity, ProgressUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AlgoControlService_WatchTaskProgressClient = grpc.ServerStreamingClient[ProgressUpdate]

func (c *algoControlServiceClient) ListTasks(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TaskList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskList)
	err := c.cc.Invoke(ctx, AlgoControlService_ListTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *algoControlServiceClient) GetTaskStatus(ctx context.Context, in *TaskIdentity, opts ...grpc.CallOption) (*TaskStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskStatus)
	err := c.cc.Invoke(ctx, AlgoControlService_GetTaskStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *algoControlServiceClient) CancelTask(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*CancelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelResponse)
	err := c.cc.Invoke(ctx, AlgoControlService_CancelTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AlgoControlServiceServer is the server API for AlgoControlService service.
// All implementations must embed UnimplementedAlgoControlServiceServer
// for forward compatibility.
//
// AlgoControlService defines the API for controlling algorithm execution
type AlgoControlServiceServer interface {
	// GetAvailableSchemes returns all registered algorithm schemes
	GetAvailableSchemes(context.Context, *Empty) (*SchemeList, error)
	// SubmitTask submits a new algorithm task for processing
	SubmitTask(context.Context, *TaskRequest) (*TaskSubmissionResponse, error)
	// CheckHealth returns the health status of the algorithm service
	CheckHealth(context.Context, *Empty) (*HealthStatus, error)
	// WatchTaskProgress streams real-time progress updates for a task
	WatchTaskProgress(*TaskIdentity, grpc.ServerStreamingServer[ProgressUpdate]) error
	// ListTasks returns all known tasks and their statuses
	ListTasks(context.Context, *Empty) (*TaskList, error)
	// GetTaskStatus returns the current status of a specific task
	GetTaskStatus(context.Context, *TaskIdentity) (*TaskStatus, error)
	// CancelTask requests cancellation of a task
	CancelTask(context.Context, *CancelRequest) (*CancelResponse, error)
	mustEmbedUnimplementedAlgoControlServiceServer()
}

// UnimplementedAlgoControlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAlgoControlServiceServer struct{}

func (UnimplementedAlgoControlServiceServer) GetAvailableSchemes(context.Context, *Empty) (*SchemeList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAvailableSchemes not implemented")
}
func (UnimplementedAlgoControlServiceServer) SubmitTask(context.Context, *TaskRequest) (*TaskSubmissionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitTask not implemented")
}
func (UnimplementedAlgoControlServiceServer) CheckHealth(context.Context, *Empty) (*HealthStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckHealth not implemented")
}
func (UnimplementedAlgoControlServiceServer) WatchTaskProgress(*TaskIdentity, grpc.ServerStreamingServer[ProgressUpdate]) error {
	return status.Error(codes.Unimplemented, "method WatchTaskProgress not implemented")
}
func (UnimplementedAlgoControlServiceServer) ListTasks(context.Context, *Empty) (*TaskList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTasks not implemented")
}
func (UnimplementedAlgoControlServiceServer) GetTaskStatus(context.Context, *TaskIdentity) (*TaskStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTaskStatus not implemented")
}
func (UnimplementedAlgoControlServiceServer) CancelTask(context.Context, *CancelRequest) (*CancelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelTask not implemented")
}
func (UnimplementedAlgoControlServiceServer) mustEmbedUnimplementedAlgoControlServiceServer() {}
func (UnimplementedAlgoControlServiceServer) testEmbeddedByValue()                            {}

// UnsafeAlgoControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AlgoControlServiceServer will
// result in compilation errors.
type UnsafeAlgoControlServiceServer interface {
	mustEmbedUnimplementedAlgoControlServiceServer()
}

func RegisterAlgoControlServiceServer(s grpc.ServiceRegistrar, srv AlgoControlServiceServer) {
	// If the following call panics, it indicates UnimplementedAlgoControlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AlgoControlService_ServiceDesc, srv)
}

func _AlgoControlService_GetAvailableSchemes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlgoControlServiceServer).GetAvailableSchemes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlgoControlService_GetAvailableSchemes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlgoControlServiceServer).GetAvailableSchemes(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlgoControlService_SubmitTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlgoControlServiceServer).SubmitTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlgoControlService_SubmitTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlgoControlServiceServer).SubmitTask(ctx, req.(*TaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlgoControlService_CheckHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlgoControlServiceServer).CheckHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlgoControlService_CheckHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlgoControlServiceServer).CheckHealth(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlgoControlService_WatchTaskProgress_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TaskIdentity)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AlgoControlServiceServer).WatchTaskProgress(m, &grpc.GenericServerStream[TaskIdentity, ProgressUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AlgoControlService_WatchTaskProgressServer = grpc.ServerStreamingServer[ProgressUpdate]

func _AlgoControlService_ListTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlgoControlServiceServer).ListTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlgoControlService_ListTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlgoControlServiceServer).ListTasks(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlgoControlService_GetTaskStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskIdentity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlgoControlServiceServer).GetTaskStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlgoControlService_GetTaskStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlgoControlServiceServer).GetTaskStatus(ctx, req.(*TaskIdentity))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlgoControlService_CancelTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlgoControlServiceServer).CancelTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlgoControlService_CancelTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlgoControlServiceServer).CancelTask(ctx, req.(*CancelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AlgoControlService_ServiceDesc is the grpc.ServiceDesc for AlgoControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AlgoControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "algorithm.AlgoControlService",
	HandlerType: (*AlgoControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAvailableSchemes",
			Handler:    _AlgoControlService_GetAvailableSchemes_Handler,
		},
		{
			MethodName: "SubmitTask",
			Handler:    _AlgoControlService_SubmitTask_Handler,
		},
		{
			MethodName: "CheckHealth",
			Handler:    _AlgoControlService_CheckHealth_Handler,
		},
		{
			MethodName: "ListTasks",
			Handler:    _AlgoControlService_ListTasks_Handler,
		},
		{
			MethodName: "GetTaskStatus",
			Handler:    _AlgoControlService_GetTaskStatus_Handler,
		},
		{
			MethodName: "CancelTask",
			Handler:    _AlgoControlService_CancelTask_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchTaskProgress",
			Handler:       _AlgoControlService_WatchTaskProgress_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/algorithm.proto",
}

const (
	ResultReceiverService_ReportResult_FullMethodName = "/algorithm.ResultReceiverService/ReportResult"
)

// ResultReceiverServiceClient is the client API for ResultReceiverService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ResultReceiverService receives results from the algorithm service
type ResultReceiverServiceClient interface {
	// ReportResult reports the completion of a task
	ReportResult(ctx context.Context, in *TaskResult, opts ...grpc.CallOption) (*Ack, error)
}

type resultReceiverServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewResultReceiverServiceClient(cc grpc.ClientConnInterface) ResultReceiverServiceClient {
	return &resultReceiverServiceClient{cc}
}

func (c *resultReceiverServiceClient) ReportResult(ctx context.Context, in *TaskResult, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, ResultReceiverService_ReportResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResultReceiverServiceServer is the server API for ResultReceiverService service.
// All implementations must embed UnimplementedResultReceiverServiceServer
// for forward compatibility.
//
// ResultReceiverService receives results from the algorithm service
type ResultReceiverServiceServer interface {
	// ReportResult reports the completion of a task
	ReportResult(context.Context, *TaskResult) (*Ack, error)
	mustEmbedUnimplementedResultReceiverServiceServer()
}

// UnimplementedResultReceiverServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedResultReceiverServiceServer struct{}

func (UnimplementedResultReceiverServiceServer) ReportResult(context.Context, *TaskResult) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportResult not implemented")
}
func (UnimplementedResultReceiverServiceServer) mustEmbedUnimplementedResultReceiverServiceServer() {}
func (UnimplementedResultReceiverServiceServer) testEmbeddedByValue()                               {}

// UnsafeResultReceiverServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResultReceiverServiceServer will
// result in compilation errors.
type UnsafeResultReceiverServiceServer interface {
	mustEmbedUnimplementedResultReceiverServiceServer()
}

func RegisterResultReceiverServiceServer(s grpc.ServiceRegistrar, srv ResultReceiverServiceServer) {
	// If the following call panics, it indicates UnimplementedResultReceiverServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ResultReceiverService_ServiceDesc, srv)
}

func _ResultReceiverService_ReportResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResultReceiverServiceServer).ReportResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResultReceiverService_ReportResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResultReceiverServiceServer).ReportResult(ctx, req.(*TaskResult))
	}
	return interceptor(ctx, in, info, handler)
}

// ResultReceiverService_ServiceDesc is the grpc.ServiceDesc for ResultReceiverService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ResultReceiverService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "algorithm.ResultReceiverService",
	HandlerType: (*ResultReceiverServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportResult",
			Handler:    _ResultReceiverService_ReportResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/algorithm.proto",
}
